# Generated by Django 4.2.7 on 2025-11-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='Inquiries',
        ),
    ]
