# Generated by Django 4.2.7 on 2025-12-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_rename_enquiry_inquiries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquiries',
            new_name='Inquiry',
        ),
    ]
