# Generated by Django 5.2.1 on 2025-09-21 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('15:00', '3 PM'), ('16:00', '4 PM'), ('17:00', '5 PM'), ('18:00', '6 PM'), ('19:00', '7 PM'), ('20:00', '8 PM')], max_length=5)),
                ('students', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('message', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Booking',
                'verbose_name_plural': 'Session Bookings',
                'ordering': ['-date', '-time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'time', 'user'), name='unique_booking_per_user_per_time')],
            },
        ),
    ]
